#!/usr/bin/env bash

# Usage: ./cert-check example.com
# Prints the expiration date of the SSL certificate of the given domain.

domain="$1"

echo | openssl s_client -servername "$domain" -connect "$domain":443 2>/dev/null | openssl x509 -noout -dates
