#!/usr/bin/env bash

# Make it possible to use this in a sub directory
cd "$(git root)" || exit

files=$(git diff --name-only --cached | fzf --header "Git unadd" --ansi)
if [[ -n $files ]]; then
		git restore --staged "$files"
fi
