#!/usr/bin/env bash

set -euo pipefail

RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${RED}Will remove changes in the following files:${NC}"
git diff --name-only
echo
echo -e "${RED}Will remove these files/dirs:${NC}"
git clean -fd --dry-run
echo
read -p "Are you sure? " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
  exit 0
fi

# Add all and reset, useful when there is a conflict
git add .
git reset

git checkout .
git clean -fd

echo
read -p "Remove review branch? " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
  exit 0
fi

reviewBranch="$(git branch --show-current)"
originalBranch=${reviewBranch%%-review}
git checkout "$originalBranch"
# git branch -D "$reviewBranch"
git branch | grep '\-review$' | xargs -n 1 git branch -D
