#!/bin/sh

RED='\033[0;31m'
NC='\033[0m' # No Color

echo "${RED}Will remove changes in the following files:${NC}"
git diff --name-only
echo
echo "${RED}Will remove these files/dirs:${NC}"
git clean -fd --dry-run
echo
read -p "Are you sure? " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
  exit 0
fi

git checkout .
git clean -fd
