#!/usr/bin/env bash

# Inspired by: https://github.com/bluz71/dotfiles/blob/master/bashrc

# Make it possible to use this in a sub directory
cd "$(git root)" || exit

previewPosition="right"

if [ "$(tput cols)" -lt 140 ]; then
	previewPosition="top"
fi

selections=$(
		git status --porcelain | \
		fzf --ansi --multi --preview-window "$previewPosition" \
			--preview 'if [ ! -f {2} ]; then
				echo "File not found"
			elif (git ls-files --error-unmatch {2} &>/dev/null); then
				git diff --color=always {2} | delta
			else
				bat --color=always --line-range :500 {2}
			fi'
		)

if [[ -n $selections ]]; then
	echo "$selections" | cut -c 4- | tr '\n' ' ' | xargs git add --verbose
fi
