#!/usr/bin/env bash

# Requires fzf

path="$1"

if [ -z "${path}" ]; then
    echo "Path is missing"
    exit 1
fi

if [ ! -f "$path" ]; then
    echo "$path does not exist, you can create it with:"
    echo ""
    echo "echo \"First 1 0\nSecond 1 0\" > $path"
    echo ""
    echo "Format: Name weight(0<weight<=1) numberOfPicks"
    exit 1
fi

content=$(cat "$path");
numberOfPicks=$(echo "$content" | awk '{ SUM=SUM+$3 } END { print SUM }')
numberOfMembers=$(echo "$content" | awk 'END { print NR }')

if [ "$numberOfPicks" -eq "0" ]; then
    # First pick mode
    picked=$(echo "$content" | awk '{ print $1 }' | fzf)
else
    # Name, picked count, goal, current state, diff between goal and current state, over or under goal
    # Sort by diff between goal and current state -> the preselected one should probably be picked
    picked=$(echo "$content" | awk -v OFS='\t' -v p="$numberOfPicks" -v m="$numberOfMembers" '{printf "%s\t%s\t%.2f\t%.2f\t%.2f\t%s\n", $1, $3, $2/m, $3/p, ($3/p) - ($2/m), ($2/m > $3/p ? "Below 😴" : "Over 🔥")}' | sort -nk5 | fzf --header "Pick one" | awk '{print $1}')
fi

if [ -z "$picked" ]; then
    exit 0
fi

# +1 on the one that was picked
echo "$content" | awk -v picked="$picked" '{ print $1, $2, ($1 == picked ? $3+1 : $3)}' > "$path"

echo "$picked was picked"
