#!/bin/bash

projectId="$1"
token="$GITLAB_TOKEN"
server="gitlab.com"

if [ -z "${projectId}" ]; then
    echo "Project ID is missing"
    exit 1
fi

curl --request DELETE --header "PRIVATE-TOKEN: $token" \
      "https://$server/api/v4/projects/$projectId/artifacts"
