#!/bin/bash

# Dependencies:
#   * httpie

# The sourced files has to set these variables:
#   * method
#   * url
#   * headers (optional)
#
# TODO
#   * Add curl as optional backend? curl -sS $method $url -H "$headers"

usage(){
  echo "Usage:"
  echo "  request -f file -p param"
  echo ""
  echo "Options:"
  echo "  -f file : source one or more files"
  echo "  -p param : one or more params"
  echo "  -o output : see httpie --print for options"
  echo ""
  exit
}

headers=""
output=""

# Parse options and arguments
while getopts "f:,p:,o:" option; do
  case $option in
    "f")
      files+=("$OPTARG")
      ;;
    "p")
      params+=("$OPTARG")
      ;;
    "o")
      output="$output$OPTARG"
      ;;
    *)
      usage
      ;;
  esac
done

if [ "$output" = "" ]; then
  output=hb
fi

# No options were provided or there was a mistake
if [ "$OPTIND" -eq "1" ] || [ "$OPTIND" -le "$#" ]; then
  usage
fi

if [ -f .env ]
then
  export $(cat .env | sed 's/#.*//g' | xargs)
fi

for file in "${files[@]}"; do
  source "$file"
done

http --print="$output" "$method" "$url" "$headers"
