#!/bin/bash

# Status monitor
# Example:
# 	Check and print status code every 20 seconds (default is 10 seconds)
#		sm example.com 20

url=$1
sleep=${2:-10}

while true
do 
    time=$(date +"%T")
    statusCode=$(curl -LI $url -o /dev/null -w '%{http_code}\n' -s)
    echo "$time $statusCode"
    sleep $sleep
done
