#!/bin/bash

# STATUS MONITOR
#
# Example:
# 	Check and print status code every 20 seconds (default is 10 seconds)
#		sm example.com 20
#
# Improved after seeing https://github.com/nickjj/lcurl

URL=$1
SLEEP=${2:-10}
TIMEOUT=${3:-120}
MAX_LOOP_COUNT=${4:-999999}
COUNTER=1

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
ORANGE='\033[0;33m'
NC='\033[0m' # No Color

if [ -z "${URL}" ]; then
    echo "URL is missing"
    exit 1
fi

while [ "${COUNTER}" -le "${MAX_LOOP_COUNT}" ]; do
    NOW="$(date +'%F %H:%M:%S')"

    output=$(curl \
        --silent \
        --location \
        --max-time "$TIMEOUT" \
        --output /dev/null \
        --write-out "%{http_code} | %{time_total}s | ${NOW} | ${COUNTER}/${MAX_LOOP_COUNT}\n" "${URL}")

    statusCode=$(echo "$output" | cut -d " " -f1)

    if [[ "$statusCode" == 2* ]]; then
        echo -e "${GREEN}$output${NC}"
    elif [[  "$statusCode" == 3*  ]]; then
        echo -e "${BLUE}$output${NC}"
    elif [[  "$statusCode" == 4*  ]]; then
        echo -e "${ORANGE}$output${NC}"
    elif [[  "$statusCode" == 5*  ]]; then
        echo -e "${RED}$output${NC}"
    else
        echo "$output"
    fi

    sleep "$SLEEP"

    ((COUNTER++))
done
