#!/bin/bash

# https://superuser.com/questions/891915/interactive-search-of-tmux-sessions/893793#893793
# https://dev.to/waylonwalker/jump-to-running-tmux-sessions-with-fzf-4p77

tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t
