#!/usr/bin/env bash

output=""

checkInternetConnection=$(tmux show -gv @checkInternetConnection)

if [ "$checkInternetConnection" -eq 1 ]; then
	if [[ $(has-internet-connection) == "1" ]]; then
		status+="OK"
		color="green"
	else
		status+="FAIL"
		color="red"
	fi
	output+="Net:#[fg=$color]$status#[default] "
fi

countStatusCakeFails=$(tmux show -gv @countStatusCakeFails)

if [ "$countStatusCakeFails" -eq 1 ]; then
	fails="$(cache 'statuscake-cli -status fail -output count' /tmp/tmux-status-statuscake)"
	if [[ "$fails" =~ ^-?[0-9]+$ ]]; then
		if [ "$fails" -eq 0 ]; then
			color="green"
		else
			color="red"
		fi
	else
			color="yellow"
	fi
	output+="SC:#[fg=$color]$fails#[default] "
fi

output+="$(tracked-time)"

echo "$output"
