#!/usr/bin/env bash

output=""

checkInternetConnection=$(tmux show -gv @checkInternetConnection)

if [ "$checkInternetConnection" -eq 1 ]; then
	if [[ $(has-internet-connection) == "1" ]]; then
		output+="connected "
	else
		output+="disconnected "
	fi
fi

output+="$(tracked-time)"

echo "$output"
